### PR TITLE
USB/FIQ: Fix bad mode access when voluntary preemption is enabled

### PR DESCRIPTION
**Pull request by carlocaione**
[endlessm/eos-shell#5907]

### CODE REVIEW

**Comment by carlocaione** [comment]
Yes. But I'd expect it to be managed by the compiler. Also here https://github.com/endlessm/linux-meson/blob/shell/5907/arch/arm/kernel/fiqasm.S#L25 in theory we are not respecting the calling convention.

**Comment by carlocaione** [comment]
Anyway it definitely makes sense to save registers onto the stack.

**Comment by dsd** [comment]
> Yes. But I'd expect it to be managed by the compiler.

I would expect the compiler to do that for C code, where it itself is managing the registers.

But when you are writing your own asm, the compiler does not get involved, since there is nothing to compile. My understanding is that it is then up to you to obey the calling convention. There are plenty of examples of C-to-asm entry points where registers are saved to the stack presumably for this reason e.g. v7_flush_kern_cache_all

I don't see where __set_fiq_regs is disobeying calling convention. If you're referring to it modifying r8-r12, that is fine because it is doing that for the FIQ banked registers. When cpsr is restored, it automatically goes back to the previous r8-r12 values for that context, which have not been modified by the function.

**Comment by carlocaione** [comment]
I'm referring to the fact that `__set_fiq_regs` is modifying R2 and R1 without saving them before onto the stack.

**Comment by carlocaione** [comment]
Ok NVM "In the prologue, push r4 to r11 to the stack". This solves the problem I guess.

**Pull request merged**
