### PR TITLE
mali: add HW id and revision to version

### PR DESCRIPTION
**Pull request by xjuan**
https://phabricator.endlessm.com/T18288

### CODE REVIEW

**Comment by dsd** [comment]
Please add a commit message explaining this - the version string was previously blank, briefly explain the new format, mention that flatpak will use it.

Instead of defining and using MODULE_VERSION_SHOW can you just directly create the  module_version_attribute and other required data?

**Comment by dsd** [comment]
Have you tested that it works OK when mali is builtin to the kernel (not as a module)?

**Comment by xjuan** [comment]
OK np, I will remove MODULE_VERSION_SHOW
BTW I have not test it as a module, since I am building the kernel with the original config

**Comment by ptomato** [comment]
Is anything still valid from this PR now that we are using the host Mali driver in flatpak?

**Comment by dsd** [comment]
obsolete

**Pull request closed without merging**
